version: '3.7'
services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    network_mode: host
    volumes: 
      - /home/secondary/github/Asteroid2d/builds/web:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf