
services:
  web:
    image: nginx:1.26.0-alpine-slim
    ports:
      - "4000:80"
    #network_mode: host
    volumes:
      - /home/radmin/github/Asteroid2d/builds/web:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
